// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/backfill-identity': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/backfill-identity.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/profile.get').default>>>>
    }
    '/api/auth/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/user.get').default>>>>
    }
    '/api/authorizations/group': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authorizations/group.delete').default>>>>
    }
    '/api/authorizations/matrix': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authorizations/matrix.get').default>>>>
    }
    '/api/authorizations/rules': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/authorizations/rules.post').default>>>>
    }
    '/api/catalogs/planteles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/catalogs/planteles.get').default>>>>
    }
    '/api/catalogs/puestos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/catalogs/puestos.get').default>>>>
    }
    '/api/cron/permanent-passes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/permanent-passes.get').default>>>>
    }
    '/api/debug/mysql-connectivity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/mysql-connectivity.get').default>>>>
    }
    '/api/directory/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/[id].put').default>>>>
    }
    '/api/directory/:id/phone': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/[id]/phone.put').default>>>>
    }
    '/api/directory/coverage': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/coverage.get').default>>>>
    }
    '/api/directory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/index.post').default>>>>
    }
    '/api/directory/public': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/public.get').default>>>>
    }
    '/api/employees/enrich': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/employees/enrich.get').default>>>>
    }
    '/api/employees/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/employees/search.get').default>>>>
    }
    '/api/kardex/:ClaveUnica': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kardex/[ClaveUnica].get').default>>>>
    }
    '/api/kardex/:nomina': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kardex/[nomina].get').default>>>>
    }
    '/api/kardex/periodos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kardex/periodos.get').default>>>>
    }
    '/api/kardex/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kardex/status.get').default>>>>
    }
    '/api/kardex/sync-trigger': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/kardex/sync-trigger.post').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/notifications/retry': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/retry.post').default>>>>
    }
    '/api/passes/:id/action': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/[id]/action.post').default>>>>
    }
    '/api/passes/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/[id]/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/[id]/index.put').default>>>>
    }
    '/api/passes/:id/notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/[id]/notify.post').default>>>>
    }
    '/api/passes/:id/print': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/[id]/print.post').default>>>>
    }
    '/api/passes/authorize/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/authorize/[token].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/authorize/[token].post').default>>>>
    }
    '/api/passes/context': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/context.get').default>>>>
    }
    '/api/passes/employee': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/employee.get').default>>>>
    }
    '/api/passes/export': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/export.post').default>>>>
    }
    '/api/passes': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/index.post').default>>>>
    }
    '/api/passes/recent': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/recent.get').default>>>>
    }
    '/api/passes/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passes/search.get').default>>>>
    }
    '/api/reports/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/export.get').default>>>>
    }
    '/api/reports/planteles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/planteles.get').default>>>>
    }
    '/api/reports/preview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/preview.get').default>>>>
    }
    '/api/routing/rules': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/routing/rules.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/routing/rules.post').default>>>>
    }
    '/api/routing/rules/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/routing/rules/[id].delete').default>>>>
    }
    '/api/stats/movements': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats/movements.get').default>>>>
    }
    '/api/users/:email/admin': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[email]/admin.put').default>>>>
    }
    '/api/users/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/stats.get').default>>>>
    }
    '/api/workspace/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workspace/search.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}