// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/11/2026, 10:36:57 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/hp/pases-digitales/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/plugins/**/*.{js,ts,mjs}","C:/Users/hp/pases-digitales/composables/**/*.{js,ts,mjs}","C:/Users/hp/pases-digitales/utils/**/*.{js,ts,mjs}","C:/Users/hp/pases-digitales/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/pases-digitales/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;